from app.workflows.models import Template, TemplateFormat, Workflow, WorkflowStep
from app.providers.workflows.sqlite import workflow_store

def seed_builtins():
    # 1. Basic Note Template
    note_tpl = Template(
        template_id="tpl_builtin_note_01",
        name="Research Note",
        description="Standard note template for research",
        template_type="NOTE",
        format=TemplateFormat.MD,
        schema_def={"title": {"type": "string", "required": True}, "content": {"type": "string", "required": True}},
        content="# {{title}}\n\n{{content}}\n\n---\n*Generated by AI Office Assistant*",
        user_id="BUILT_IN",
        status="ACTIVE"
    )
    workflow_store.save_template(note_tpl)

    # 2. Research to Note Workflow
    research_wf = Workflow(
        workflow_id="wf_builtin_research_01",
        name="Research to Note",
        description="Search knowledge base and create a summarized note",
        version=1,
        inputs_schema={"query": {"type": "string", "required": True}},
        user_id="BUILT_IN",
        steps=[
            WorkflowStep(
                step_id="search",
                skill="knowledge_search",
                input_mapping={"query": "{{query}}"},
                output_key="search_results"
            ),
            WorkflowStep(
                step_id="summarize",
                skill="knowledge_answer", # Assuming this exists or using a generic text_summarize
                input_mapping={"query": "Summarize these findings: {{search_results}}"},
                output_key="summary"
            ),
            WorkflowStep(
                step_id="create_note",
                skill="template_render", # We need a TemplateRenderSkill!
                input_mapping={
                    "template_id": note_tpl.template_id,
                    "inputs": {"title": "Research: {{query}}", "content": "{{summary}}"}
                },
                output_key="rendered_note"
            )
        ]
    )
    workflow_store.save_workflow(research_wf)
